### PR TITLE
fix: add the `useHttp` option to the missing places

### LINKED ISSUE #378: [BUG] `useHttp` is not passed to request functions and routes factories
## Bug Report

**Describe the bug**

`useHttp` is not passed to the routes factory functions and the request function (`get`, `post`, `delete`).

**To Reproduce**

Steps and commands to reproduce the behavior. Please provide clear code snippets that always reproduce the bug.
Running this script, with a patched `@interledger/open-payments` package to see if the `useHttp` option is being used or not:
```ts
import { createUnauthenticatedClient } from "@interledger/open-payments";

const client = await createUnauthenticatedClient({
    useHttp: true,
});

await client.walletAddress.get({
    url: "https://localhost:3010/client",
});
```

will result in:
```
[PATCHED] 'useHttp' in 'checkUrlProtocol': undefined
{"level":50,"time":1700569881397,"pid":32795,"hostname":"Radus-MacBook-Pro-14.local","name":"Open Payments Client","errorDescription":"write EPROTO C01EBDDB01000000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:\n","msg":"Error making Open Payments GET request"}
/Users/radu/dev/web-monetization-script/node_modules/.pnpm/@interledger+open-payments@6.1.0_patch_hash=rqtnfdefv5gtohzzymff6lzqby/node_modules/@interledger/open-payments/dist/client/requests.js:119
```

**Expected behavior**

If `useHttp` is set to `true`, all URLs should be converted to `http`.

### PR DESCRIPTION
**Pull request by raducristianpopa**
## Context

Closes #378.

### CODE REVIEW

File: packages/open-payments/src/client/index.ts [hunk 1]
```diff
@@ -118,9 +121,36 @@ const parseKey = (
   }
 }
 
-const createDeps = async (
-  args: Partial<CreateAuthenticatedClientArgs>
-): Promise<ClientDeps> => {
+const createUnauthenticatedDeps = async ({
```
Comment (raducristianpopa) [inline packages/open-payments/src/client/index.ts:124]: Thought it would be okay to separate the unauthenticated dependencies from the authenticated ones. This way, when initializing an unauthenticated client, the authentication server OpenAPI schema will not be loaded.

File: packages/open-payments/src/client/index.ts [hunk 2]
```diff
@@ -30,11 +30,14 @@ export * from './error'
 export interface BaseDeps {
   axiosInstance: AxiosInstance
   logger: Logger
-  useHttp?: boolean
+  useHttp: boolean
```
Comment (raducristianpopa) [inline packages/open-payments/src/client/index.ts:33]: Made the `useHttp` dependency required so we can get an error whenever we are not passing it.

File: packages/open-payments/src/client/token.ts [hunk 3]
```diff
@@ -30,18 +26,14 @@ export const rotateToken = async (
 }
 
 export const revokeToken = async (
-  deps: RouteDeps,
+  deps: BaseDeps,
```
Comment (raducristianpopa) [inline packages/open-payments/src/client/token.ts:29]: Token functions were using `RouteDeps` instead of `BaseDeps` which as well.

**Review by mkurapov — APPROVED** [review]
Thanks!
